const ADD_CONTACT = 'ADD_CONTACT'
const FETCH_CONTACT = 'FETCH_CONTACT'
const UPDATE_CONTACT = 'UPDATE_CONTACT'
const FETCH_ALL_CONTACTS = 'FETCH_ALL_CONTACTS'


export {
  ADD_CONTACT,
  FETCH_CONTACT,
  UPDATE_CONTACT,
  FETCH_ALL_CONTACTS
}

